import React, {useEffect, useState} from 'react'
import Head from 'next/head'
import { Container} from '@components/ui'
import MultiStepper from "../../components/stepper/MultiStepper";

const ProjectNavigation = () => {

  return (
    <div className="w-full h-full" style={{ backgroundColor: "#FCFCFC" }}>
      <Head>
        <title>Stormlands</title>
        <meta name="Meta nema" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>
        {/* <MultiStepper></MultiStepper> */}
      </Container>
    </div>
  );
}

export default ProjectNavigation