import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Sidenav from "@layout/Sidenav/Sidenav";
import { Modal } from "@components/ui";
import ProjectCreate from "@components/project/ProjectCreate/ProjectCreate";
import Container from "@components/ui/Container";
import { useRouter } from "next/router";
import { useEffect } from "react";

const Home: NextPage = () => {
  const Router = useRouter();
  useEffect(() => {
    // Forward to new project for now
    Router.push("projects/new-project");
  }, []);
  return (
    <>
      <Head>
        <title>Stormlands</title>
        <meta name="Meta nema" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="mt-10"></div>
    </>
  );
};

export default Home;
